# Core types and utilities — eagerly imported (lightweight)
from .framework_bridges import (
    DeepAgentsBridge,
    FrameworkRunResult,
    LangGraphBridge,
    PydanticAIBridge,
)
from .hybrid_retrieval import HybridInMemoryRetriever
from .live_integration_harness import (
    IntegrationCheckResult,
    IntegrationHarnessReport,
    LiveIntegrationHarness,
)
from .manager import ContextManager, WeightConfig
from .models import ContextItem, ContextKind, ContextPacket
from .providers import AnthropicMessagesAdapter, OllamaChatAdapter, OpenAIChatAdapter
from .retrieval import (
    ChromaRetriever,
    InMemoryVectorRetriever,
    PineconeRetriever,
    RetrievedChunk,
    Retriever,
)
from .scoring import EmbeddingScorer, KeywordOverlapScorer, RelevanceScorer, cosine_similarity
from .quality import (
    FaithfulnessJudge,
    FaithfulnessVerdict,
    QuoteOnlyFaithfulnessJudge,
    average_precision,
    mrr,
    ndcg_at_k,
    precision_at_k,
    recall_at_k,
)
from .runtime_base import (
    AuditLogger,
    BaseCommanderMixin,
    BaseIntegrationCommanderMixin,
    ExecutionTask,
    HTTPJSONAdapterBase,
    IdempotencyStore,
    InMemoryIdempotencyStore,
    IntegrationActionResult,
    IntegrationExecutionTask,
    JSONLAuditLogger,
    NoOpAuditLogger,
    ToolExecutionResult,
    unique_preserve,
)
from .summarization import (
    ConversationSummarizer,
    HeuristicConversationSummarizer,
    RollingSummaryConfig,
)
from .tokenizer import ApproxTokenCounter, TiktokenCounter, TokenCounter

# Domain runtimes — lazy-loaded to avoid import-time penalty.
# Each runtime module is only imported when one of its symbols is accessed.
# This mapping is used by __getattr__ below.
_LAZY_MODULES: dict[str, str] = {
    # AML runtime
    "AMLActionResult": "aml_runtime",
    "AMLDecision": "aml_runtime",
    "AMLExecutionPolicy": "aml_runtime",
    "AMLExecutionReport": "aml_runtime",
    "AMLExecutionStats": "aml_runtime",
    "AMLKYCFincrimeCommander": "aml_runtime",
    "AMLRoute": "aml_runtime",
    "AMLSignal": "aml_runtime",
    "CaseActionAdapter": "aml_runtime",
    "HTTPCaseActionAdapter": "aml_runtime",
    "HTTPSanctionsScreenAdapter": "aml_runtime",
    "HTTPTransactionGraphAdapter": "aml_runtime",
    "InMemoryCaseActionAdapter": "aml_runtime",
    "InMemorySanctionsScreenAdapter": "aml_runtime",
    "InMemoryTransactionGraphAdapter": "aml_runtime",
    "NoOpCaseActionAdapter": "aml_runtime",
    "NoOpSanctionsScreenAdapter": "aml_runtime",
    "NoOpTransactionGraphAdapter": "aml_runtime",
    "SanctionsScreenAdapter": "aml_runtime",
    "TransactionGraphAdapter": "aml_runtime",
    "build_case_action_adapter_from_env": "aml_runtime",
    "build_sanctions_screen_adapter_from_env": "aml_runtime",
    "build_transaction_graph_adapter_from_env": "aml_runtime",
    # Anthropic agentic text system
    "AgenticSDKBindings": "anthropic_agentic_text_system",
    "AnthropicAgenticTextSystem": "anthropic_agentic_text_system",
    "TextManipulationToolkit": "anthropic_agentic_text_system",
    "TextOperationReport": "anthropic_agentic_text_system",
    # Claims runtime
    "CatastropheClaimsCommander": "claims_runtime",
    "CatastropheClaimsExecutionReport": "claims_runtime",
    "ClaimAssessment": "claims_runtime",
    "ClaimIndicators": "claims_runtime",
    "ClaimsExecutionPolicy": "claims_runtime",
    "ClaimsExecutionStats": "claims_runtime",
    "ClaimsToolExecutionResult": "claims_runtime",
    "FraudAdapter": "claims_runtime",
    "HTTPFraudAdapter": "claims_runtime",
    "HTTPPayoutAdapter": "claims_runtime",
    "HTTPPolicyAdapter": "claims_runtime",
    "InMemoryFraudAdapter": "claims_runtime",
    "InMemoryPayoutAdapter": "claims_runtime",
    "InMemoryPolicyAdapter": "claims_runtime",
    "NoOpFraudAdapter": "claims_runtime",
    "NoOpPayoutAdapter": "claims_runtime",
    "NoOpPolicyAdapter": "claims_runtime",
    "PayoutAdapter": "claims_runtime",
    "PolicyAdapter": "claims_runtime",
    "build_fraud_adapter_from_env": "claims_runtime",
    "build_payout_adapter_from_env": "claims_runtime",
    "build_policy_adapter_from_env": "claims_runtime",
    # Clinical operations runtime
    "AcuityIntelAdapter": "clinical_operations_runtime",
    "BedCapacityAdapter": "clinical_operations_runtime",
    "ClinicalActionAdapter": "clinical_operations_runtime",
    "ClinicalActionResult": "clinical_operations_runtime",
    "ClinicalDecision": "clinical_operations_runtime",
    "ClinicalExecutionPolicy": "clinical_operations_runtime",
    "ClinicalExecutionReport": "clinical_operations_runtime",
    "ClinicalExecutionStats": "clinical_operations_runtime",
    "ClinicalOperationsCommander": "clinical_operations_runtime",
    "ClinicalRoute": "clinical_operations_runtime",
    "ClinicalSignal": "clinical_operations_runtime",
    "HTTPAcuityIntelAdapter": "clinical_operations_runtime",
    "HTTPBedCapacityAdapter": "clinical_operations_runtime",
    "HTTPClinicalActionAdapter": "clinical_operations_runtime",
    "InMemoryAcuityIntelAdapter": "clinical_operations_runtime",
    "InMemoryBedCapacityAdapter": "clinical_operations_runtime",
    "InMemoryClinicalActionAdapter": "clinical_operations_runtime",
    "NoOpAcuityIntelAdapter": "clinical_operations_runtime",
    "NoOpBedCapacityAdapter": "clinical_operations_runtime",
    "NoOpClinicalActionAdapter": "clinical_operations_runtime",
    "build_acuity_intel_adapter_from_env": "clinical_operations_runtime",
    "build_bed_capacity_adapter_from_env": "clinical_operations_runtime",
    "build_clinical_action_adapter_from_env": "clinical_operations_runtime",
    # Contact center runtime
    "ContactCenterActionResult": "contact_center_autopilot_runtime",
    "ContactCenterAutopilotCommander": "contact_center_autopilot_runtime",
    "ContactCenterDecision": "contact_center_autopilot_runtime",
    "ContactCenterExecutionPolicy": "contact_center_autopilot_runtime",
    "ContactCenterExecutionReport": "contact_center_autopilot_runtime",
    "ContactCenterExecutionStats": "contact_center_autopilot_runtime",
    "ContactCenterRoute": "contact_center_autopilot_runtime",
    "ContactCenterSignal": "contact_center_autopilot_runtime",
    "ContactResolutionActionAdapter": "contact_center_autopilot_runtime",
    "CustomerProfileAdapter": "contact_center_autopilot_runtime",
    "HTTPContactResolutionActionAdapter": "contact_center_autopilot_runtime",
    "HTTPCustomerProfileAdapter": "contact_center_autopilot_runtime",
    "HTTPPolicyGuardrailAdapter": "contact_center_autopilot_runtime",
    "InMemoryContactResolutionActionAdapter": "contact_center_autopilot_runtime",
    "InMemoryCustomerProfileAdapter": "contact_center_autopilot_runtime",
    "InMemoryPolicyGuardrailAdapter": "contact_center_autopilot_runtime",
    "NoOpContactResolutionActionAdapter": "contact_center_autopilot_runtime",
    "NoOpCustomerProfileAdapter": "contact_center_autopilot_runtime",
    "NoOpPolicyGuardrailAdapter": "contact_center_autopilot_runtime",
    "PolicyGuardrailAdapter": "contact_center_autopilot_runtime",
    "build_contact_resolution_action_adapter_from_env": "contact_center_autopilot_runtime",
    "build_customer_profile_adapter_from_env": "contact_center_autopilot_runtime",
    "build_policy_guardrail_adapter_from_env": "contact_center_autopilot_runtime",
    # Contract negotiation runtime
    "ClauseRiskAdapter": "contract_negotiation_runtime",
    "ContractActionAdapter": "contract_negotiation_runtime",
    "ContractActionResult": "contract_negotiation_runtime",
    "ContractDecision": "contract_negotiation_runtime",
    "ContractExecutionPolicy": "contract_negotiation_runtime",
    "ContractExecutionReport": "contract_negotiation_runtime",
    "ContractExecutionStats": "contract_negotiation_runtime",
    "ContractNegotiationCommander": "contract_negotiation_runtime",
    "ContractRoute": "contract_negotiation_runtime",
    "ContractSignal": "contract_negotiation_runtime",
    "HTTPClauseRiskAdapter": "contract_negotiation_runtime",
    "HTTPContractActionAdapter": "contract_negotiation_runtime",
    "HTTPNegotiationPrecedentAdapter": "contract_negotiation_runtime",
    "InMemoryClauseRiskAdapter": "contract_negotiation_runtime",
    "InMemoryContractActionAdapter": "contract_negotiation_runtime",
    "InMemoryNegotiationPrecedentAdapter": "contract_negotiation_runtime",
    "NegotiationPrecedentAdapter": "contract_negotiation_runtime",
    "NoOpClauseRiskAdapter": "contract_negotiation_runtime",
    "NoOpContractActionAdapter": "contract_negotiation_runtime",
    "NoOpNegotiationPrecedentAdapter": "contract_negotiation_runtime",
    "build_clause_risk_adapter_from_env": "contract_negotiation_runtime",
    "build_contract_action_adapter_from_env": "contract_negotiation_runtime",
    "build_negotiation_precedent_adapter_from_env": "contract_negotiation_runtime",
    # Emergency operations runtime
    "EmergencyOperationsCommander": "emergency_operations_runtime",
    "EOCActionAdapter": "emergency_operations_runtime",
    "EOCActionResult": "emergency_operations_runtime",
    "EOCDecision": "emergency_operations_runtime",
    "EOCExecutionPolicy": "emergency_operations_runtime",
    "EOCExecutionReport": "emergency_operations_runtime",
    "EOCExecutionStats": "emergency_operations_runtime",
    "EOCRoute": "emergency_operations_runtime",
    "EOCSignal": "emergency_operations_runtime",
    "HazardIntelAdapter": "emergency_operations_runtime",
    "HTTPEOCActionAdapter": "emergency_operations_runtime",
    "HTTPHazardIntelAdapter": "emergency_operations_runtime",
    "HTTPLogisticsCapacityAdapter": "emergency_operations_runtime",
    "InMemoryEOCActionAdapter": "emergency_operations_runtime",
    "InMemoryHazardIntelAdapter": "emergency_operations_runtime",
    "InMemoryLogisticsCapacityAdapter": "emergency_operations_runtime",
    "LogisticsCapacityAdapter": "emergency_operations_runtime",
    "NoOpEOCActionAdapter": "emergency_operations_runtime",
    "NoOpHazardIntelAdapter": "emergency_operations_runtime",
    "NoOpLogisticsCapacityAdapter": "emergency_operations_runtime",
    "build_eoc_action_adapter_from_env": "emergency_operations_runtime",
    "build_hazard_intel_adapter_from_env": "emergency_operations_runtime",
    "build_logistics_capacity_adapter_from_env": "emergency_operations_runtime",
    # Grid outage runtime
    "CriticalLoadAdapter": "grid_outage_runtime",
    "GridActionAdapter": "grid_outage_runtime",
    "GridActionResult": "grid_outage_runtime",
    "GridDecision": "grid_outage_runtime",
    "GridExecutionPolicy": "grid_outage_runtime",
    "GridExecutionReport": "grid_outage_runtime",
    "GridExecutionStats": "grid_outage_runtime",
    "GridOutageCommander": "grid_outage_runtime",
    "GridRoute": "grid_outage_runtime",
    "GridSignal": "grid_outage_runtime",
    "GridTelemetryAdapter": "grid_outage_runtime",
    "HTTPCriticalLoadAdapter": "grid_outage_runtime",
    "HTTPGridActionAdapter": "grid_outage_runtime",
    "HTTPGridTelemetryAdapter": "grid_outage_runtime",
    "InMemoryCriticalLoadAdapter": "grid_outage_runtime",
    "InMemoryGridActionAdapter": "grid_outage_runtime",
    "InMemoryGridTelemetryAdapter": "grid_outage_runtime",
    "NoOpCriticalLoadAdapter": "grid_outage_runtime",
    "NoOpGridActionAdapter": "grid_outage_runtime",
    "NoOpGridTelemetryAdapter": "grid_outage_runtime",
    "build_critical_load_adapter_from_env": "grid_outage_runtime",
    "build_grid_action_adapter_from_env": "grid_outage_runtime",
    "build_grid_telemetry_adapter_from_env": "grid_outage_runtime",
    # Legacy modern migration runtime
    "DependencyGraphAdapter": "legacy_modern_migration_runtime",
    "HTTPDependencyGraphAdapter": "legacy_modern_migration_runtime",
    "HTTPMigrationActionAdapter": "legacy_modern_migration_runtime",
    "HTTPSystemInventoryAdapter": "legacy_modern_migration_runtime",
    "InMemoryDependencyGraphAdapter": "legacy_modern_migration_runtime",
    "InMemoryMigrationActionAdapter": "legacy_modern_migration_runtime",
    "InMemorySystemInventoryAdapter": "legacy_modern_migration_runtime",
    "LegacyMigrationActionResult": "legacy_modern_migration_runtime",
    "LegacyMigrationDecision": "legacy_modern_migration_runtime",
    "LegacyMigrationExecutionPolicy": "legacy_modern_migration_runtime",
    "LegacyMigrationExecutionReport": "legacy_modern_migration_runtime",
    "LegacyMigrationExecutionStats": "legacy_modern_migration_runtime",
    "LegacyMigrationRoute": "legacy_modern_migration_runtime",
    "LegacyMigrationSignal": "legacy_modern_migration_runtime",
    "LegacyModernMigrationCommander": "legacy_modern_migration_runtime",
    "MigrationActionAdapter": "legacy_modern_migration_runtime",
    "NoOpDependencyGraphAdapter": "legacy_modern_migration_runtime",
    "NoOpMigrationActionAdapter": "legacy_modern_migration_runtime",
    "NoOpSystemInventoryAdapter": "legacy_modern_migration_runtime",
    "SystemInventoryAdapter": "legacy_modern_migration_runtime",
    "build_dependency_graph_adapter_from_env": "legacy_modern_migration_runtime",
    "build_migration_action_adapter_from_env": "legacy_modern_migration_runtime",
    "build_system_inventory_adapter_from_env": "legacy_modern_migration_runtime",
    # Manufacturing runtime
    "HTTPLineTelemetryAdapter": "manufacturing_runtime",
    "HTTPMaintenanceHistoryAdapter": "manufacturing_runtime",
    "HTTPManufacturingActionAdapter": "manufacturing_runtime",
    "InMemoryLineTelemetryAdapter": "manufacturing_runtime",
    "InMemoryMaintenanceHistoryAdapter": "manufacturing_runtime",
    "InMemoryManufacturingActionAdapter": "manufacturing_runtime",
    "LineTelemetryAdapter": "manufacturing_runtime",
    "MaintenanceHistoryAdapter": "manufacturing_runtime",
    "ManufacturingActionAdapter": "manufacturing_runtime",
    "ManufacturingActionResult": "manufacturing_runtime",
    "ManufacturingDecision": "manufacturing_runtime",
    "ManufacturingExecutionPolicy": "manufacturing_runtime",
    "ManufacturingExecutionReport": "manufacturing_runtime",
    "ManufacturingExecutionStats": "manufacturing_runtime",
    "ManufacturingRootCauseCommander": "manufacturing_runtime",
    "ManufacturingRoute": "manufacturing_runtime",
    "ManufacturingSignal": "manufacturing_runtime",
    "NoOpLineTelemetryAdapter": "manufacturing_runtime",
    "NoOpMaintenanceHistoryAdapter": "manufacturing_runtime",
    "NoOpManufacturingActionAdapter": "manufacturing_runtime",
    "build_line_telemetry_adapter_from_env": "manufacturing_runtime",
    "build_maintenance_history_adapter_from_env": "manufacturing_runtime",
    "build_manufacturing_action_adapter_from_env": "manufacturing_runtime",
    # Pharmacovigilance runtime
    "FAERSAdapter": "pharmacovigilance_runtime",
    "HTTPFAERSAdapter": "pharmacovigilance_runtime",
    "HTTPLotTraceabilityAdapter": "pharmacovigilance_runtime",
    "HTTPSafetyActionAdapter": "pharmacovigilance_runtime",
    "InMemoryFAERSAdapter": "pharmacovigilance_runtime",
    "InMemoryLotTraceabilityAdapter": "pharmacovigilance_runtime",
    "InMemorySafetyActionAdapter": "pharmacovigilance_runtime",
    "LotTraceabilityAdapter": "pharmacovigilance_runtime",
    "NoOpFAERSAdapter": "pharmacovigilance_runtime",
    "NoOpLotTraceabilityAdapter": "pharmacovigilance_runtime",
    "NoOpSafetyActionAdapter": "pharmacovigilance_runtime",
    "PharmacovigilanceCommander": "pharmacovigilance_runtime",
    "PharmacovigilanceExecutionPolicy": "pharmacovigilance_runtime",
    "PharmacovigilanceExecutionReport": "pharmacovigilance_runtime",
    "PharmacovigilanceExecutionStats": "pharmacovigilance_runtime",
    "PVActionResult": "pharmacovigilance_runtime",
    "PVDecision": "pharmacovigilance_runtime",
    "PVRoute": "pharmacovigilance_runtime",
    "PVSignal": "pharmacovigilance_runtime",
    "SafetyActionAdapter": "pharmacovigilance_runtime",
    "build_faers_adapter_from_env": "pharmacovigilance_runtime",
    "build_lot_traceability_adapter_from_env": "pharmacovigilance_runtime",
    "build_safety_action_adapter_from_env": "pharmacovigilance_runtime",
    # Provider SDK bridges
    "AnthropicSDKBridge": "provider_sdk",
    "CerebrasSDKBridge": "provider_sdk",
    "OllamaSDKBridge": "provider_sdk",
    "OpenAIResponsesSDKBridge": "provider_sdk",
    "PerplexityResult": "provider_sdk",
    "SpeculativeDecodingMetrics": "provider_sdk",
    # Regulatory change runtime
    "ComplianceActionAdapter": "regulatory_change_runtime",
    "ControlCoverageAdapter": "regulatory_change_runtime",
    "HTTPComplianceActionAdapter": "regulatory_change_runtime",
    "HTTPControlCoverageAdapter": "regulatory_change_runtime",
    "HTTPRegulationIntelAdapter": "regulatory_change_runtime",
    "InMemoryComplianceActionAdapter": "regulatory_change_runtime",
    "InMemoryControlCoverageAdapter": "regulatory_change_runtime",
    "InMemoryRegulationIntelAdapter": "regulatory_change_runtime",
    "NoOpComplianceActionAdapter": "regulatory_change_runtime",
    "NoOpControlCoverageAdapter": "regulatory_change_runtime",
    "NoOpRegulationIntelAdapter": "regulatory_change_runtime",
    "RegulationIntelAdapter": "regulatory_change_runtime",
    "RegulatoryActionResult": "regulatory_change_runtime",
    "RegulatoryChangeCommander": "regulatory_change_runtime",
    "RegulatoryDecision": "regulatory_change_runtime",
    "RegulatoryExecutionPolicy": "regulatory_change_runtime",
    "RegulatoryExecutionReport": "regulatory_change_runtime",
    "RegulatoryExecutionStats": "regulatory_change_runtime",
    "RegulatoryRoute": "regulatory_change_runtime",
    "RegulatorySignal": "regulatory_change_runtime",
    "build_compliance_action_adapter_from_env": "regulatory_change_runtime",
    "build_control_coverage_adapter_from_env": "regulatory_change_runtime",
    "build_regulation_intel_adapter_from_env": "regulatory_change_runtime",
    # SOC runtime
    "EDRAdapter": "soc_runtime",
    "ExecutionPolicy": "soc_runtime",
    "HTTPEDRAdapter": "soc_runtime",
    "HTTPIAMAdapter": "soc_runtime",
    "HTTPSIEMAdapter": "soc_runtime",
    "IAMAdapter": "soc_runtime",
    "InMemoryEDRAdapter": "soc_runtime",
    "InMemoryIAMAdapter": "soc_runtime",
    "InMemorySIEMAdapter": "soc_runtime",
    "NoOpEDRAdapter": "soc_runtime",
    "NoOpIAMAdapter": "soc_runtime",
    "NoOpSIEMAdapter": "soc_runtime",
    "SIEMAdapter": "soc_runtime",
    "SOCExecutionReport": "soc_runtime",
    "SOCExecutionStats": "soc_runtime",
    "SOCIncidentCommander": "soc_runtime",
    "SOCIndicators": "soc_runtime",
    "build_edr_adapter_from_env": "soc_runtime",
    "build_iam_adapter_from_env": "soc_runtime",
    "build_siem_adapter_from_env": "soc_runtime",
    # Supply chain runtime
    "ActionRoute": "supply_chain_runtime",
    "FulfillmentActionAdapter": "supply_chain_runtime",
    "HTTPFulfillmentActionAdapter": "supply_chain_runtime",
    "HTTPLaneDelayAdapter": "supply_chain_runtime",
    "HTTPSupplierRiskAdapter": "supply_chain_runtime",
    "InMemoryFulfillmentActionAdapter": "supply_chain_runtime",
    "InMemoryLaneDelayAdapter": "supply_chain_runtime",
    "InMemorySupplierRiskAdapter": "supply_chain_runtime",
    "IntegrationCallResult": "supply_chain_runtime",
    "LaneDelayAdapter": "supply_chain_runtime",
    "NoOpFulfillmentActionAdapter": "supply_chain_runtime",
    "NoOpLaneDelayAdapter": "supply_chain_runtime",
    "NoOpSupplierRiskAdapter": "supply_chain_runtime",
    "SupplierRiskAdapter": "supply_chain_runtime",
    "SupplyChainControlTowerCommander": "supply_chain_runtime",
    "SupplyChainExecutionPolicy": "supply_chain_runtime",
    "SupplyChainExecutionReport": "supply_chain_runtime",
    "SupplyChainExecutionStats": "supply_chain_runtime",
    "SupplyDecision": "supply_chain_runtime",
    "SupplySignal": "supply_chain_runtime",
    "build_fulfillment_action_adapter_from_env": "supply_chain_runtime",
    "build_lane_delay_adapter_from_env": "supply_chain_runtime",
    "build_supplier_risk_adapter_from_env": "supply_chain_runtime",
    # Tri-provider pipeline
    "CandidateRanking": "tri_provider_pipeline",
    "StageOutcome": "tri_provider_pipeline",
    "TriProviderPipeline": "tri_provider_pipeline",
    "UseCaseExecutionReport": "tri_provider_pipeline",
    # Tri-provider use cases
    "USE_CASE_INDEX": "tri_provider_use_cases",
    "USE_CASES": "tri_provider_use_cases",
    "AnthropicStageSpec": "tri_provider_use_cases",
    "CerebrasStageSpec": "tri_provider_use_cases",
    "OpenAIStageSpec": "tri_provider_use_cases",
    "TriProviderUseCaseSpec": "tri_provider_use_cases",
    "validate_use_case_catalog": "tri_provider_use_cases",
}


def __getattr__(name: str):
    """Lazy-load domain runtime symbols on first access."""
    if name in _LAZY_MODULES:
        import importlib

        module = importlib.import_module(f".{_LAZY_MODULES[name]}", __package__)
        value = getattr(module, name)
        # Cache on the module so subsequent accesses skip __getattr__
        globals()[name] = value
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


# __all__ includes both eagerly and lazily loaded symbols
__all__ = [
    # Eagerly loaded core types
    "AuditLogger",
    "BaseCommanderMixin",
    "BaseIntegrationCommanderMixin",
    "ExecutionTask",
    "HTTPJSONAdapterBase",
    "IntegrationActionResult",
    "IntegrationExecutionTask",
    "unique_preserve",
    "ApproxTokenCounter",
    "AnthropicMessagesAdapter",
    "ChromaRetriever",
    "ConversationSummarizer",
    "ContextItem",
    "ContextKind",
    "ContextManager",
    "ContextPacket",
    "DeepAgentsBridge",
    "EmbeddingScorer",
    "FaithfulnessJudge",
    "FaithfulnessVerdict",
    "FrameworkRunResult",
    "HeuristicConversationSummarizer",
    "HybridInMemoryRetriever",
    "IdempotencyStore",
    "InMemoryIdempotencyStore",
    "InMemoryVectorRetriever",
    "IntegrationCheckResult",
    "IntegrationHarnessReport",
    "JSONLAuditLogger",
    "KeywordOverlapScorer",
    "LangGraphBridge",
    "LiveIntegrationHarness",
    "NoOpAuditLogger",
    "OllamaChatAdapter",
    "OpenAIChatAdapter",
    "PineconeRetriever",
    "PydanticAIBridge",
    "QuoteOnlyFaithfulnessJudge",
    "RelevanceScorer",
    "Retriever",
    "RetrievedChunk",
    "RollingSummaryConfig",
    "TiktokenCounter",
    "TokenCounter",
    "ToolExecutionResult",
    "WeightConfig",
    "average_precision",
    "cosine_similarity",
    "mrr",
    "ndcg_at_k",
    "precision_at_k",
    "recall_at_k",
    # Lazily loaded domain runtime symbols
    *_LAZY_MODULES.keys(),
]
